// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwQllzBTtWegd2UUDLMOVjjLVF48L0O4',
    appId: '1:465656103333:web:cca85d712e8d3bdaf4e84c',
    messagingSenderId: '465656103333',
    projectId: 'workly-9f673',
    authDomain: 'workly-9f673.firebaseapp.com',
    storageBucket: 'workly-9f673.firebasestorage.app',
    measurementId: 'G-RPKDPZ9VS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPXRSuHRqoQ_MDGPK4Vl_CygCkj35NDt0',
    appId: '1:465656103333:android:f30bb558a79c47e3f4e84c',
    messagingSenderId: '465656103333',
    projectId: 'workly-9f673',
    storageBucket: 'workly-9f673.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqw6_deQcnoIYDlqzofPWyvDDE3ncDEQ',
    appId: '1:465656103333:ios:b501e1a37f630f99f4e84c',
    messagingSenderId: '465656103333',
    projectId: 'workly-9f673',
    storageBucket: 'workly-9f673.firebasestorage.app',
    iosBundleId: 'com.example.jobTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKqw6_deQcnoIYDlqzofPWyvDDE3ncDEQ',
    appId: '1:465656103333:ios:b501e1a37f630f99f4e84c',
    messagingSenderId: '465656103333',
    projectId: 'workly-9f673',
    storageBucket: 'workly-9f673.firebasestorage.app',
    iosBundleId: 'com.example.jobTinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjwQllzBTtWegd2UUDLMOVjjLVF48L0O4',
    appId: '1:465656103333:web:884353547757e9a1f4e84c',
    messagingSenderId: '465656103333',
    projectId: 'workly-9f673',
    authDomain: 'workly-9f673.firebaseapp.com',
    storageBucket: 'workly-9f673.firebasestorage.app',
    measurementId: 'G-767XRHYHRD',
  );
}
